"""Compatibility re-exports for spherical geometry mathematics."""

from TerraLab.scene.spherical_math import (
    SkyCoord,
    _clamp,
    _wrap_angle_180,
    _wrap_angle_360,
    altaz_to_ra_dec,
    angular_delta_signed,
    angular_distance,
    calculate_sun_times,
    destination_point,
    get_sun_alt_az,
    gmst_deg,
    julian_day,
    lst_deg,
    ra_dec_to_alt_az,
    screen_to_sky,
    sky_to_vector,
    slerp_arc_points,
    vector_to_sky,
)

__all__ = [
    "SkyCoord",
    "_clamp",
    "_wrap_angle_180",
    "_wrap_angle_360",
    "sky_to_vector",
    "vector_to_sky",
    "angular_distance",
    "slerp_arc_points",
    "destination_point",
    "screen_to_sky",
    "angular_delta_signed",
    "julian_day",
    "gmst_deg",
    "lst_deg",
    "ra_dec_to_alt_az",
    "altaz_to_ra_dec",
    "get_sun_alt_az",
    "calculate_sun_times",
]
